[general]
import = [
    "~/.config/alacritty/themes/themes/gruvbox_material_hard_dark.toml"
]

[font]
size = 20

[font.normal]
family = "BerkeleyMono Nerd Font"
style = "Regular"

[window]
padding = { x = 15, y = 2 }

[window.dimensions]
columns = 60
lines = 20

[selection]
save_to_clipboard = true

[terminal]
shell = { program = "/bin/zsh", args = ["-l"] }
