[font]
size = 20

[font.normal]
family = "JetbrainsMono Nerd Font"
style = "Regular"

[window]
padding = { x = 15, y = 2 }

[window.dimensions]
columns = 60
lines = 20

[general]
import = [
    "~/.config/alacritty/themes/themes/gruvbox_material_hard_dark.toml"
]
